
services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "5080:5080"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:5080"